name: Update Validators Info
on:
  schedule:
    # Run once per day at 19:00 UTC or 12PM PST
    - cron:  '0 19 * * *'
jobs:
  update-validators:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         token: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
     - uses: actions/setup-node@v1
       with:
         node-version: 12
     - name: Install Dependencies
       run: npm ci
     - name: Run scripts
       run: npm run gen:validators:tezos
     - name: Run test
       run: npm t
     - name: Commit changes test pased
       if: success()
       uses: stefanzweifel/git-auto-commit-action@v4.1.2
       with:
         commit_user_name: trust-wallet-merge-bot
         commit_user_email: mergebot@trustwallet.com
         commit_message: Update validators info